export { default as LoginPage } from './LoginPage'
export { default as OAuthPage } from './OAuthPage'
export { default as LandingPage } from './LandingPage'
export { default as MyPage } from './MyPage'
export { default as MorePage } from './MorePage'
export { default as NotFoundPage } from './NotFoundPage'
